name: Access Secrets 
on: 
  push:
    branches: 
      - main
      
jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Run JavaScript 
        env: 
          SUPABASE_API_URL: ${{ secrets.SUPABASE_API_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
        run:
          node index.js
      
